services:
  nginx:
    image: nginx:mainline-alpine
    ports:
      - 80:80
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./index.html:/www/html/index.html
    depends_on:
      - backend1
      - backend2
    networks:
      - backend

  backend1:
    build: .
    networks:
      - backend

  backend2:
    build: .
    networks:
      - backend

  # or simply, just do
  # backend: ...
  # and run `docker compose up --scale backend=n`

networks:
  backend:
